"""empty message

Revision ID: 4059073caf09
Revises: 
Create Date: 2021-07-22 04:44:40.549203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4059073caf09'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=True),
    sa.Column('descripcion', sa.String(length=50), nullable=True),
    sa.Column('paleta', sa.Integer(), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=True),
    sa.Column('sku', sa.String(length=50), nullable=True),
    sa.Column('inventario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['inventario_id'], ['inventario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pedidos__productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=True),
    sa.Column('producto_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedido.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pedidos__productos')
    op.drop_table('producto')
    # ### end Alembic commands ###
